### PR TITLE
Fix Requirements are out of sync with upstream.  #158

### LINKED ISSUE #158: Requirements are out of sync with upstream.
The requirements are out of sync with upstream. 

Namely `- jinja2 >=2.9,<3` in [L42](https://github.com/conda-forge/conan-feedstock/blob/master/recipe/meta.yaml#L42), is outdated by [this commit](https://github.com/conan-io/conan/commit/bbdec0a377c8e30bf5ef0ad68ff4745bba43b20d).

### PR DESCRIPTION
**Pull request by ruilvo**
Fixes #158.

### CODE REVIEW

**Comment by wolfv** [comment]
I think you could run `pip check` as part of the test commands to make sure deps are fine.
Examples: https://github.com/search?q=org%3Aconda-forge+pip+check&type=code

**Comment by abloemert** [comment]
Thank you very much @ruilvo for the PR. Did you plan to apply the suggestion from @wolfv ?

**Comment by abloemert** [comment]
Great, thank you both!

**Comment by abloemert** [comment]
Oops, I now realize that we forgot to bump the build number.

**Pull request merged**
