### PR TITLE
update conan to latest version (v1.3.3)

### PR DESCRIPTION
**Pull request by abloemert**

### CODE REVIEW

**Comment by jakirkham** [comment]
Any interest in helping maintain, @abloemert? :)

**Comment by windelbouwman** [comment]
Yes, but the question more is, should we merge this PR? Since build indicates a failure, but I do not know what this means.

**Comment by windelbouwman** [comment]
Btw, there are more pull requests (PR) made by a bot to upgrade the version, but these builds indicate failure. Why is this?

**Comment by abloemert** [comment]
> Btw, there are more pull requests (PR) made by a bot to upgrade the version, but these builds indicate failure. Why is this?

I assume this is because a missing dependency: `deprecation`

**Comment by abloemert** [comment]
> Any interest in helping maintain, @abloemert? :)

I just joined as member of conda-forge ;)

**Comment by abloemert** [comment]
Can I just merge this PR myself?

**Comment by windelbouwman** [comment]
Yes, you can. But the other pull requests generated by a robot also changed lots of stuff. I do not know if the conda format was changed. Maybe you can compare #8 to this PR and see if only the `deprecated` package needed to be added.

**Comment by jakirkham** [comment]
> I just joined as member of conda-forge ;)

Great, glad to have you. :)

**Comment by jakirkham** [comment]
> But the other pull requests generated by a robot also changed lots of stuff. I do not know if the conda format was changed.

Normally it [re-renders the feedstock]( https://conda-forge.org/docs/conda_smithy.html ). This takes care of non-recipe changes (e.g. updates in the CI config files, repo documentation, etc.).

Then it does a version bump. Currently it doesn't handle updating dependencies, but it is something we'd like to solve. Expect this last point caused the CI failures previously.

Hope that helps. Please feel free to ask questions.

**Pull request merged**
